# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/XML-RPC-Fast-0.6

DESCRIPTION="No description available"
HOMEPAGE="http://search.cpan.org/search?query=XML-RPC-Fast&mode=dist"
SRC_URI="mirror://cpan/authors/id/M/MO/MONS/XML-RPC-Fast-0.6.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~amd64"

DEPEND=">=dev-perl/lib-abs-0.90
	>=dev-perl/XML-Hash-LX-0.06
	dev-perl/Test-NoWarnings
	dev-perl/libwww-perl
	dev-perl/XML-LibXML
	dev-lang/perl"
