# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/XML-Hash-LX-0.06

DESCRIPTION="No description available"
HOMEPAGE="http://search.cpan.org/search?query=XML-Hash-LX&mode=dist"
SRC_URI="mirror://cpan/authors/id/M/MO/MONS/XML-Hash-LX-0.06.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~amd64"

DEPEND=">=dev-perl/lib-abs-0.90
	dev-perl/XML-LibXML
	dev-lang/perl"
