image: registry.gitlab.fem-net.de/gentoo/fem-overlay-ci-image:master

stages:
  - repoman
  - overlint
  - pkgcheck
  - manifest

variables:
  DISTDIR: ./tmp_distdir
  NOCOLOR: "false"
  PKGCHECK_COMMON_OPTS: "--color true"

repoman_all:
  stage: repoman
  script:
    - repoman full -x -j4
  needs: []
  rules:
    - if: "$CI_COMMIT_BRANCH == 'master'"

repoman_commits:
  stage: repoman
  script:
    - git fetch
    - ./tools/repoman_changed_files.sh
  needs: []
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"

overlint:
  stage: overlint
  script:
    - overlint-cli .
  needs: []
  rules:
    - if: "$CI_COMMIT_BRANCH == 'master'"

pkgcheck_all:
  stage: pkgcheck
  script:
    - pkgcheck scan $PKGCHECK_COMMON_OPTS
  needs: []
  rules:
    - if: "$CI_COMMIT_BRANCH == 'master'"

pkgcheck_commits:
  stage: pkgcheck
  script:
    - git fetch
    - pkgcheck scan $PKGCHECK_COMMON_OPTS --commits origin/master..HEAD
  needs: []
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"


.manifest:
  stage: manifest
  before_script:
    - git fetch
  script:
    - ./tools/manifest_packages.sh

  needs: []

  cache:
    - key: manifest
      paths:
        - "${DISTDIR}"

manifest_all:
  extends: .manifest
  variables:
    MANIFEST_ONLY_DIFF: "false"

  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

manifest_commits:
  extends: .manifest
  variables:
    MANIFEST_ONLY_DIFF: "true"

  rules:
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"
