image: gentoo/stage3

stages:
  - repoman
  - overlint
  - pkgcheck

default:
  before_script:
    - ./tools/sync_portage.sh

repoman:
  stage: repoman
  script:
    - emerge --quiet --noreplace app-portage/repoman dev-vcs/git
    - repoman full -x -j4
  cache:
    key: fem-overlay-gentoo-stage3
    paths:
      - ./tmp
  needs: []

overlint:
  stage: overlint
  script:
    - emerge --quiet --noreplace app-portage/overlint
    - overlint-cli .
  cache:
    key: fem-overlay-gentoo-stage3
    paths:
      - ./tmp
  needs: []

pkgcheck:
  stage: pkgcheck
  script:
    - emerge --quiet --noreplace dev-util/pkgcheck
    - pkgcheck scan --exit --checks="-ManifestCheck"
  cache:
    key: fem-overlay-gentoo-stage3
    paths:
      - ./tmp
  needs: []
