image: registry.gitlab.fem-net.de/gentoo/fem-overlay-ci-image:master

stages:
  - repoman
  - overlint
  - pkgcheck

repoman_all:
  stage: repoman
  script:
    - repoman full -x -j4
  needs: []
  except: [merge_requests]

repoman_commits:
  stage: repoman
  script:
    - git fetch
    - ./tools/repoman_changed_files.sh
  needs: []
  only: [merge_requests]

overlint:
  stage: overlint
  script:
    - overlint-cli .
  needs: []
  rules:
    - when: always

pkgcheck_all:
  stage: pkgcheck
  script:
    - pkgcheck scan
  needs: []
  except: [merge_requests]

pkgcheck_commits:
  stage: pkgcheck
  script:
    - git fetch
    - pkgcheck scan --commits origin/master..HEAD
  needs: []
  only: [merge_requests]
