#!/sbin/runscript
# Copyright 1999-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

depend() {
	need net
}

start() {
	ebegin "Starting nutcracker"
	start-stop-daemon --user ${USER}:${GROUP} --start --quiet \
		--exec /usr/bin/nutcracker -- -d -c ${CONFFILE}
	eend $? "Failed to start nutcracker"
}

stop() {
	ebegin "Stopping nutcracker"
		start-stop-daemon --stop --quiet --exec /usr/sbin/nutcracker
	eend $?
}
