# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/Digest-MD5-File-0.07

DESCRIPTION="Digest::MD5 Sub Class to use paths directly"
HOMEPAGE="http://search.cpan.org/search?query=Digest-MD5-File&mode=dist"
SRC_URI="mirror://cpan/authors/id/D/DM/DMUEY/Digest-MD5-File-0.07.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~amd64"

DEPEND="dev-perl/libwww-perl
	dev-lang/perl"
