#!/sbin/runscript

PHPSLOT=${SVCNAME#php-fpm-}

if [[ $PHPSLOT == "php-fpm" ]]; then
	PHPSLOT=$(eselect php show fpm)
else
	PHPSLOT=php${PHPSLOT}
fi


PHP_FPM_CONF="/etc/php/fpm-${PHPSLOT}/php-fpm.conf"


opts="depend start stop reload"

depend() {
        need net
				use apache2 lighttpd nginx
}

start() {
        ebegin "Starting PHP FastCGI server"
        start-stop-daemon --start --exec /usr/lib/${PHPSLOT}/bin/php-fpm -- -y "${PHP_FPM_CONF}"
        eend $?
}

stop() {
        ebegin "Stopping PHP FastCGI server"
        start-stop-daemon --stop --exec /usr/lib/${PHPSLOT}/bin/php-fpm
        eend $?
}

