#!/sbin/runscript
# source function library

depend() {
	use net
}

start() {
        ebegin "Starting ${SVCNAME}"

	start-stop-daemon --start --exec /usr/sbin/lldpd --pidfile /var/run/lldpd.pid -- ${LLDPD_FLAGS}
	eend $? "Check your logs to see why startup failed"
	
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --stop --exec /usr/sbin/lldpd --pidfile /var/run/lldpd.pid
	eend $?
}

