#!/sbin/runscript
# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

depend() {
       use logger net
}
 
start() {
       ebegin "Starting UCARP"
       start-stop-daemon --start --background --make-pidfile --pidfile ${UCARP_PIDFILE} --quiet --startas ${UCARP_EXEC} -- ${UCARP_OPTS}
       eend $?
}
 
stop()  {
        ebegin "Stopping UCARP"
        start-stop-daemon --stop --pidfile ${UCARP_PIDFILE}
        eend $?
}
