#!/sbin/runscript
# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

depend() {
       use logger net
}

start() {
       ebegin "Starting UCARP"
       start-stop-daemon --start --background --make-pidfile --pidfile /var/run/ucarp.pid --quiet --exec /usr/sbin/ucarp -- ${UCARP_OPTS}
       eend $?
}

stop()  {
        ebegin "Stopping UCARP"
        start-stop-daemon --stop --pidfile /var/run/ucarp.pid
        eend $?
}
