#!/sbin/runscript
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

depend() {
        after net
}

start() {
        ebegin "Starting garbd"

        # Find a working node
        for ADDRESS in ${GALERA_NODES} 0; do
                HOST=$(echo $ADDRESS | cut -d \: -f 1 )
                PORT=$(echo $ADDRESS | cut -d \: -f 2 )
                PORT=${PORT:-$GALERA_PORT}
                nc $HOST $PORT -w 1 2>/dev/null >/dev/null && break
        done
        if [ ${ADDRESS} == "0" ]; then
                eend "None of the nodes in ${GALERA_NODES} is accessible"
                return 1
        fi

        OPTIONS="-d -a gcomm://$ADDRESS"
        [ -n "$GALERA_GROUP" ]   && OPTIONS="$OPTIONS -g $GALERA_GROUP"
        [ -n "$GALERA_OPTIONS" ] && OPTIONS="$OPTIONS -o $GALERA_OPTIONS"
        [ -n "$LOG_FILE" ]       && OPTIONS="$OPTIONS -l $LOG_FILE"
                                                                                    
        start-stop-daemon --start --quiet \
                --exec /usr/bin/garbd -- $OPTIONS
        eend $? "Failed to start garbd"
}

stop() {
        ebegin "Stopping garbd"
        start-stop-daemon --stop --quiet --exec /usr/bin/garbd
        eend $? "Failed to stop garbd"
}

